### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by tuncer** [comment]
If you want to skip building if either rustfmt or clippy fails, then you can use `needs: <some-job>` to add a dependency.

**Comment by ArturKovacs** [comment]
Yes, please add both the fmt check and clippy as a build dependency and I'll merge this.

**Comment by tuncer** [comment]
Done. I left fmt check independent, since a clippy run can be useful regardless of formatting issues.

**Comment by ArturKovacs** [comment]
> a clippy run can be useful regardless of formatting issues

That's true. But I don't think it's a justification for allowing builds to succeed when the code is not formatted properly. To give a more extreme example let's say that there's a crate which only works if there's a `needed.json` file. Let's say that there's a job that checks for the existance of this file. In this case it's obvious that the check wouldn't be made optional just because clippy gives useful information.

So if person X makes a pull requests which has both formatting and clippy errors but fails at rustfmt, they will run `cargo fmt`, push again and they will see that it still won't build because this time clippy didn't succeed.

**Comment by tuncer** [comment]
OK, updated.

**Comment by ArturKovacs** [comment]
Yaay thanks!

**Pull request merged**
