### PR TITLE
Avoid deleting folders and fix X freeze

### LINKED ISSUE #166: Deleting files slowly, then deleting the folder
As @akimdi wrote at https://github.com/ArturKovacs/emulsion/pull/164#issuecomment-752750084:

It hangs a little for a few seconds when I delete files one by one and there are no files left in the folder and then throws this error

```
Error occurred while loading image: Could not got current file descriptor
Error occurred while loading image: Could not got current file descriptor
Error while updating directory Error(DirError(Other("No such file or directory (os error 2)")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```

### PR DESCRIPTION
**Pull request by ArturKovacs**
Fixes #166

### CODE REVIEW

**Comment by ArturKovacs** [comment]
@akimdi could you test if this fixes
- the slow deletion
- the folder getting deleted at the end

**Comment by akimdi** [comment]
> @akimdi could you test if this fixes
> 
>     * the slow deletion
> 
>     * the folder getting deleted at the end

Doesn't work at all. Even deleting files usually doesn't work.

**Comment by ArturKovacs** [comment]
Should be fixed now ☺️

**Comment by akimdi** [comment]
> Should be fixed now relaxed

Everything works fine and doesn't freeze. Thank you :)

**Pull request merged**
