### PR TITLE
Optional AVIF support

### PR DESCRIPTION
**Pull request by Aloso**
This adds optional support for [AVIF](https://aomediacodec.github.io/av1-avif/) files. It can be enabled with `--features=avif`. Note that it requires `cmake`.

I can confirm that it works on Arch Linux. You can test if it works on your platform with this file: [avif.zip](https://github.com/ArturKovacs/emulsion/files/4825418/avif.zip)

There's a [tracking issue](https://github.com/image-rs/image/issues/1152) for AVIF support in `image-rs`, but that's unlikely to be implemented soon (`image-rs` only accepts pure Rust codecs).

If you don't think adding this is a good idea, feel free to close this PR.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
Closing and re-opening to trigger a re-build.

**Comment by paolobarbolini** [comment]
I think you are missing Meson, Ninja and NASM.

* [Ubuntu](https://github.com/njaard/libavif-rs/blob/cebf1cae6713164080cf37f5ebbb2d5cd62e4da7/.github/workflows/ci.yml#L104) (please note we are [using 20.04](https://github.com/njaard/libavif-rs/blob/cebf1cae6713164080cf37f5ebbb2d5cd62e4da7/.github/workflows/ci.yml#L66) to get the latest nasm required by Dav1d)
* [macOS](https://github.com/njaard/libavif-rs/blob/cebf1cae6713164080cf37f5ebbb2d5cd62e4da7/.github/workflows/ci.yml#L109)
* I haven't written the Windows build but I think they are available via Chocolatey

**Comment by Aloso** [comment]
@paolobarbolini thanks for your help! I'll see if I get it to work on ubuntu and macos

**Comment by Aloso** [comment]
Note that I **disabled the `avif` feature for Windows**, since I don't know how to install the dependencies (mesa, ninja, nasm) on Windows.

**Comment by paolobarbolini** [comment]
I can make a PR to this repo when I get the chance to also add it to the libavif-rs CI

**Comment by ArturKovacs** [comment]
> I can make a PR to this repo when I get the chance to also add it to the libavif-rs CI

@paolobarbolini  I'm not sure what this means. Could you explain?

**Comment by paolobarbolini** [comment]
> > I can make a PR to this repo when I get the chance to also add it to the libavif-rs CI
> 
> @paolobarbolini I'm not sure what this means. Could you explain?

When I write the tests for Windows for the libavif-rs repo I can also open a PR for this one, since the configuration is very similar

**Comment by paolobarbolini** [comment]
Update: I started working on the Windows support https://github.com/njaard/libavif-rs/pull/15 but at the moment it's not working for some reason.

**Comment by ArturKovacs** [comment]
I love to hear that @paolobarbolini! Unfortunately I don't have much time for open source development but I can see that the relevant PR (https://github.com/njaard/libavif-rs/pull/18) was merged so updating the libavif-rs dependency should be done for Emulsion but I'm not sure when will I get to it.

**Comment by paolobarbolini** [comment]
We'll come out with a v0.3 for the Windows support as well as other changes. At the moment there aren't any breaking changes in the `libavif-image` crate, so you should be able to just bump the version once it comes out. You can also try it right now by importing from git, but because of a bug in libgit2 cloning the repository might fail in some cargo versions.

Your CI isn't currently testing AVIF on Windows, and that will require the Windows job to be updated to install the libavif required build dependencies ([build dependencies](https://github.com/njaard/libavif-rs/blob/41f4fad11b27379dfe394adf7a3234a69c851d76/.github/workflows/ci.yml#L93-L106) | [tests](https://github.com/njaard/libavif-rs/blob/41f4fad11b27379dfe394adf7a3234a69c851d76/.github/workflows/ci.yml#L113-L118)), but that can be done later.

**Pull request merged**
