### PR TITLE
Improve legibility of info popup

### PR DESCRIPTION
**Pull request by Aloso**
Changes the font, font size and spacing of the info popup. I find this much easier to read than the previous image, when scaled down:

### Before/after

before-after

The new font is [Fira Sans](https://github.com/mozilla/Fira) (also available on [Google Fonts](https://fonts.google.com/specimen/Fira+Sans)).

### CODE REVIEW

**Comment by ArturKovacs** [comment]
I like this improvement, there are two things.

1. I really like the separator line between the paragraphs and the input bindings table.
2. I opened the odt and saw that the bindings were not aligned. Are you using Libre Office to edit this file? Also if you haven't, please consider using the Export function from Libre Office to export the document directly into a png. Then for example I saved it with Gimp as a gray image with high compression to squeeze out as many bytes as possible.

<details>
  <summary>This is what Libre Office 6.3.5.2 shows me for the odt file.</summary>

image

</details>

**Comment by Aloso** [comment]
I did use LibreOffice, I don't know why the tabs aren't shown.

I can make the font a bit smaller to add the separator again.

I also exported it from LibreOffice and converted it to grayscale with GIMP. The result was not as small as the previous image, so I used compress-or-die.com.

**Comment by Aloso** [comment]
@ArturKovacs the issues should be fixed now.

**Comment by ArturKovacs** [comment]
Now the odt is better, but it's so strange that on my machine Libre Office still displays the document differently. But it doesn't matter. The png is good, so I'm merging this. 🙂

**Comment by Aloso** [comment]
Thanks!

If the document isn't displayed correctly, you might have to install the [font](https://github.com/mozilla/Fira) on your PC.

**Pull request merged**
