### PR TITLE
Change panning to left-click.

### LINKED ISSUE #130: Change panning to left click
right click is inconvenient on my trackball and most viewers seem to use left-click pan. I'm not sure how you'd want to do it, but the most basic combining the left/right click in picture_widget.rs seems to work fine for me. configurable mouse buttons (and maybe configurable double-press for any key/button) would also work but I can see how that'd be a challenge.
```rust
MouseButton::Left => {
	let mut borrowed = self.data.borrow_mut();
	if state == ElementState::Pressed {
		borrowed.click = borrowed.hover;
		borrowed.panning = borrowed.hover;
		if borrowed.hover {
			let now = Instant::now();
			let duration_since_last_click =
				now.duration_since(borrowed.last_click_time);
			borrowed.last_click_time = now;
			if duration_since_last_click < Duration::from_millis(250) {
				match borrowed.window.upgrade() {
					Some(window) => {
						let fullscreen = !window.fullscreen();
						window.set_fullscreen(fullscreen);
						borrowed.bottom_bar.set_visible(!fullscreen);
					}
					None => unreachable!(),
				}
			}
		}
	} else {
		borrowed.panning = false;
		borrowed.click = false;
	}
	borrowed.render_validity.invalidate();
}
```
the only thing I might add is not triggering the double-click action when you pan, so quick short pans don't toggle full screen, but honestly it's hard to accidentally trigger that and it might make the double-tap much harder on a touch screen.

### PR DESCRIPTION
**Pull request by ArturKovacs**
Panning used to be activated by right-click. With this PR that's changed to use the left-click instead, which is more intuitive and user-friendly.

Closes #130

### CODE REVIEW

**Comment by ArturKovacs** [comment]
@retrotails, @Aloso what do you think?

**Comment by Aloso** [comment]
I'd prefer panning with left click. That's what I'm used to from some other applications.

**Comment by retrotails** [comment]
lgtm, the right click warning seems a little unnecessary but I guess that's temporary until you have a right-click context menu, if you still plan that.

**Comment by ArturKovacs** [comment]
@retrotails yeah the warning is temporary, I think it's only going to be there in the next version but it should be there for at least a month or of course when the context menu is implemented it should be removed. So yeah I'm absolutely still planning to make that right-click context menu. I'm progressing a bit slower around these days with emulsion stuff but I'm still intending to work on many of the open issues.

**Pull request merged**
