### PR TITLE
Fail CI on clippy warnings

### PR DESCRIPTION
**Pull request by vn971**
This commit should now fail because clippy warnings aren't actually fixed at the moment.

If/when I see CI failing, it'd make sense to proceed with fixing the warnings

### CODE REVIEW

**Comment by vn971** [comment]
Done, the CI now runs clippy and fails it as it should. If this PR gets greenlighted, the warnings can actually be fixed

**Comment by vn971** [comment]
Or better yet, we can merge this together with https://github.com/ArturKovacs/emulsion/pull/185 by @benediktwerner

**Comment by ArturKovacs** [comment]
#185 should be merged before this.

**Comment by ArturKovacs** [comment]
Please merge the master branch back into this one, so that the tests can succeed.

**Comment by vn971** [comment]
Done

**Comment by vn971** [comment]
Note that `libavif-image` feature is NOT enabled for the clippy check in CI, because it didn't build. I didn't have time to address this, but if anybody wants to improve the CI by making it possible (e.g. install required deps), feel free to do so

**Comment by vn971** [comment]
Clippy now fails as it should - does anybody want to take over?

**Comment by benediktwerner** [comment]
Well, clippy now shouldn't fail anymore after #185. But #179 introduced another one which I missed. I just opened #187 to fix this.

**Comment by ArturKovacs** [comment]
Alright, #187 got merged, if you merge master back into this one, it should succeed now.

**Comment by vn971** [comment]
Thanks! Done :heavy_check_mark:

**Comment by ArturKovacs** [comment]
Awesome! Thanks to the both of you!

**Pull request merged**
