### PR TITLE
[WIP] Allow fetching image over HTTP

### LINKED ISSUE #12: Feature: reqwest dependency
I noticed a lot of the compile time is spent building the reqwest crate (and its deps), that is as far as I see needed for the update checker.
It would be nice if this check could be an optional feature. (Still being the default, though)

But if it's already there, the program could use reqwest if an URL is passed as argument instead of a file.

Does that sound good?

### PR DESCRIPTION
**Pull request by Aloso**
EDIT: This branch doesn't work since #56  was merged.

Allows opening images over HTTP or HTTPS with

```sh
emulsion https://some_url
```

Since I'm not deeply familiar with the code base, this might contain bugs, but I hope it's useful anyway.

Fixes #12

### CODE REVIEW

**Comment by Aloso** [comment]
I noticed that using the slider after opening a URL results in an error. @ArturKovacs how could I fix this?

**Comment by ArturKovacs** [comment]
Hmm I'll think about this but this one may not be able to make it into the next release. Also this is going to have a lot of conflicts #56. In fact you may want to reimplement this "from sratch" after #56. I hope you understand that I would really like to merge that as I've been sitting on that branch for a while now and I would like to pay a bit more attention to other things.

**Comment by Aloso** [comment]
That's alright, I'll revisit this once animated GIFs are merged.

**Comment by tuncer** [comment]
To reduce dependencies, have we considered a smaller http crate? For instance, I've successfully used [ureq](https://crates.io/crates/ureq) before?

**Comment by Aloso** [comment]
I think that's a good idea.

Ping @ArturKovacs

**Comment by ArturKovacs** [comment]
Yeah we are using reqwest in blocking mode anyways and I don't think there will ever be a reason to change it to async. So yes ureq seems like a very good alternative. @tuncer feel free to make an issue and to even to implement it if you'd like :)

**Comment by tuncer** [comment]
Sure, I can do that. Are we going to merge this and make the switch, or should we replace reqwest in master first?

**Comment by Aloso** [comment]
@tuncer This branch doesn't work at the moment, so we can replace `reqwest` in master first.

**Comment by tuncer** [comment]
Done, see #63.

**Pull request closed without merging**
