### PR TITLE
Command line ergonomics

### LINKED ISSUE #64: Improve usability in command line
Command line users would appreciate the following features:

- [ ] 1. Passing `--version` or `-V` should print the name and version of the program
- [ ] 2. Passing `--help` or `-h` should print the name, version, author, description and usage
- [ ] 3. ~Piping a command to emulsion should work~ &nbsp; see #67 
- [ ] 4. When the program is used incorrectly, an error message should be displayed
- [ ] 5. Errors should be printed to `stderr` instead of `stdout`
- [ ] 6. Debugging info should not be printed, at least in release builds

Some additional details:

- 1\. and 2. could be solved by using `clap`, but implementing it by hand isn't hard either.

- 3\. will allow e.g. `curl http://some_url | emulsion` which is awesome!

    Unfortunately it requires some refactoring to support displaying an image that doesn't correspond to a file in the file system. However, this is required for #12 anyway. 

- 4\. means that an error is displayed if no arguments are provided and emulsion is not used as a pipe, or too many arguments are provided.

- 5\. means that some `println!` statements should be replaced with `eprintln!`

- 6\. means that some `println!` statements should be removed

### PR DESCRIPTION
**Pull request by Aloso**
Errors are now correctly printed to stderr with `eprintln!()`.

Emulsion now use [clap](https://crates.io/crates/clap), and accepts two options, `--version/-V` and `--help/-h`.

This should make it easy to add new options, if the need arises.

In case of an error (if ~no file or~ more than one file is provided, or an unsupported option is used), an error message is printed and no window is opened.

(This also silences some warnings, e.g. by adding `_` to identifiers)

Closes #64 

Try it:

```
❯ cargo run -- -h
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/emulsion -h`
emulsion 2.0.0
Artur Barnabas <kovacs.artur.barnabas@gmail.com>
A fast and minimalistic image viewer
https://arturkovacs.github.io/emulsion-website/

USAGE:
    emulsion <PATH>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <PATH>    The file path of the image

CONFIGURATION:
    config file: /home/ludwig/.config/emulsion/cfg.toml
    cache file:  /home/ludwig/.cache/emulsion/cache.toml
```

### CODE REVIEW

**Comment by ArturKovacs** [comment]
I see you went for the good ol' homemade argument parsing. But you do know there are crates for this stuff, like [clap](https://docs.rs/clap/latest/clap/)?

What's the reasoning behind using capital `V` for the version shorthand instead of a lowercase `v`?

**Comment by Aloso** [comment]
`-V` is used because `-v` is often short for `--verbose` (clap uses `-V` for `--version` by default).

I'll change it to use clap if you want!

**Comment by Aloso** [comment]
It uses clap now, as suggested.

**Comment by ArturKovacs** [comment]
Great!

This does not compile with networking enabled. Also I'd like to ask you to make it optional to specify an image path. In most environments Emulsion supports drag and drop, and for example I use that often.

**Comment by ArturKovacs** [comment]
Yaay!

**Pull request merged**
