### PR TITLE
Update winit to 22.2

### LINKED ISSUE #128: Crash on app open
On Windows the app crashes upon run without displaying any UI or image.

Content of `panic.txt` below
```
===

--
buffering RedrawRequested event
--

Location /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4\src\libstd\macros.rs:13:23

   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: DefSubclassProc
   8: DefSubclassProc
   9: CallWindowProcW
  10: CallWindowProcW
  11: glPushClientAttrib
  12: CallWindowProcW
  13: DispatchMessageW
  14: IsWindowVisible
  15: KiUserCallbackDispatcher
  16: NtUserDispatchMessage
  17: DispatchMessageW
  18: InputFocusMonitorCreate
  19: InputFocusMonitorCreate
  20: TF_Notify
  21: TF_Notify
  22: TF_SendLangBandMsg
  23: <unknown>
  24: DllUnregisterServer
  25: TF_SendLangBandMsg
  26: TF_SendLangBandMsg
  27: TF_SetDefaultRemoteKeyboardLayout
  28: SetInputScopes2
  29: CtfImeProcessCicHotkey
  30: CtfImeProcessCicHotkey
  31: CtfImeAssociateFocus
  32: CtfImeAssociateFocus
  33: CtfImeAssociateFocus
  34: ImmSetActiveContext
  35: GetWindow
  36: GetWindowRgnBox
  37: GetDlgItem
  38: GetDlgItem
  39: CallWindowProcW
  40: DispatchMessageW
  41: IsWindowVisible
  42: KiUserCallbackDispatcher
  43: NtUserMessageCall
  44: GetWindowTextW
  45: GetWindowTextW
  46: CallWindowProcW
  47: CallWindowProcW
  48: DefSubclassProc
  49: DefSubclassProc
  50: DefSubclassProc
  51: DefSubclassProc
  52: CallWindowProcW
  53: CallWindowProcW
  54: glPushClientAttrib
  55: CallWindowProcW
  56: DispatchMessageW
  57: IsWindowVisible
  58: KiUserCallbackDispatcher
  59: NtUserShowWindow
  60: <unknown>
  61: <unknown>
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: <unknown>
  67: BaseThreadInitThunk
  68: RtlUserThreadStart

===
```

### PR DESCRIPTION
**Pull request by ArturKovacs**
Closes #128.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
https://github.com/rust-windowing/winit/pull/1496 fixed the issue that seems to cause #128. This PR updates winit to the newest version that contains the referred winit PR.

@RagibHasin please check if this fixes the issue for you

**Comment by Aloso** [comment]
@ArturKovacs pro tip: You can write

```toml
gelatin = { path = "./subcrates/gelatin", version = "0.4" }
```

so `cargo run` uses the local copy of the crate and publishing on crates.io still works.

**Comment by ArturKovacs** [comment]
Thanks @Aloso, I'll change that right away! Where does one learn such things?

**Comment by RagibHasin** [comment]
So, far it is working alright with nightly, with that warning though.

<pre>
$ cargo run                                                           
warning: variable does not need to be mutable                         
   --> src\picture_widget.rs:590:10                                   
    |                                                                 
590 |                     let mut borrowed = self.data.borrow_mut();  
    |                         ----^^^^^^^^                            
    |                         |                                       
    |                         help: remove this `mut`                 
    |                                                                 
    = note: `#[warn(unused_mut)]` on by default                       
                                                                      
warning: 1 warning emitted                                            
                                                                      
    Finished dev [unoptimized + debuginfo] target(s) in 2.48s         
     Running `target\debug\emulsion.exe`                              
</pre>

**Comment by Aloso** [comment]
> Thanks @Aloso, I'll change that right away! Where does one learn such things?

I learned just recently when reading [this RFC](https://github.com/rust-lang/rfcs/blob/master/text/2906-cargo-workspace-deduplicate.md).

**Comment by ArturKovacs** [comment]
@RagibHasin thank you for checking! And yeah I'll fix that warning sometime soon :D but it's not related to this issue so I'll just merge this as it is.

@Aloso hmm I just found that this is also part of the [documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) I just haven't stumbled upon it. But yes, one can definitely learn a lot from just reading miscellaneous resources about Rust.

**Pull request merged**
