### PR TITLE
Fix for #11

### PR DESCRIPTION
**Pull request by ArturKovacs**
The `before_draw` function of the widgets is now called during the `MainEventsCleared` phase instead of the `RedrawRequested` phase.

### CODE REVIEW

**Comment by tuncer** [comment]
Quick test results of this branch on Wayland are that it (1) causes 50% cpu load while it should be idling, and (2) there's an uncaught error due to unwrap in start_event_loop when you press the close button in titlebar. No such unwrap error happens when you exit with ESC.  None of the issues happen with this branch on X11.

To be clear, it does start up without blocking in set_title().

**Comment by ArturKovacs** [comment]
> it (1) causes 50% cpu load while it should be idling

I experienced a similar behaviour myself. This might be fixed when #27 or #13 gets resolved, and this is not strictry related to the issue that this PR addresses so I don't think it should block from merging.

> (2) there's an uncaught error due to unwrap in start_event_loop when you press the close button in the titlebar

I could not reproduce this.

With that said, the Wayland version has further shortcommings like the window not being shown at the proper location or the window title not being set at all. There is a chance that these are current limitations of winit. These all would need further investigation and they fall out of the scope of the addressed issue.

**Comment by tuncer** [comment]
It happened with Weston, haven't tried another Wayland compositor.

**Comment by tuncer** [comment]
I think you can merge this, as it doesn't affect X11 negatively while also fixing the set_title() bug.

**Pull request merged**
