### PR TITLE
Allow controlling the camera with the keyboard

### LINKED ISSUE #159: Allow zooming and panning to be bound to key inputs
Currently the only way to zoom is to scroll and the only way to pan the view is clicking and dragging with the cursor.

The config should allow specifying custom keyboard input for these. Although I think these still shouldn't have a keyboard input by default.

### PR DESCRIPTION
**Pull request by ArturKovacs**
Closes #159 

With this, the configuration accepts the following bindings 
```
[bindings]
zoom_in = ["x"]
zoom_out = ["z"]
pan_left = ["j"]
pan_right = ["l"]
pan_up = ["i"]
pan_down = ["k"]
```

### CODE REVIEW

**Comment by ArturKovacs** [comment]
@akimdi could you check if this does what you needed? You'd need to have rust installed to be able to build and run this so if you can't check this that's completely fine, I can just merge this as-is.

**Comment by akimdi** [comment]
@ArturKovacs  Everything works for me. Thank you. Can I remap the keys?

**Comment by ArturKovacs** [comment]
> Can I remap the keys?

Abolutely, that should be possible :) The guide on the website might help with that: https://arturkovacs.github.io/emulsion-website/bindings.html

Report back if something doesn't work.

**Comment by ArturKovacs** [comment]
@akimdi Could you remap the keys the way you wanted?

**Comment by akimdi** [comment]
@ArturKovacs  Yes, but I found some bugs during testing.
1) It hangs a little for a few seconds when I delete files one by one and there are no files left in the folder and then throws this error
```
Error occurred while loading image: Could not got current file descriptor
Error occurred while loading image: Could not got current file descriptor
Error while updating directory Error(DirError(Other("No such file or directory (os error 2)")), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
```
2) Not everywhere can create .Trash-1000 folder. For example, cannot do it in my ram folder I suspect that this is due to access rights. Other apps can do this.
```
Error while moving file '"1.jpg"' to trash: Remove { code: Some(1) }
```
3) Can't assign ```-```
for example
```
[bindings]
zoom_in = ["+"]
zoom_out = ["-"]
```
Isn't working for me.

You are making an amazing product. Thanks for everything. Happy New Year 🎄

**Comment by akimdi** [comment]
This is what my config file looks like now
[https://github.com/akimdi/emulsion/blob/master/cfg.toml](https://github.com/akimdi/emulsion/blob/master/cfg.toml)

**Comment by ArturKovacs** [comment]
1. I opened #166
2. I added this information to #163  
3. I opened https://github.com/ArturKovacs/emulsion-website/issues/6

> You are making an amazing product. Thanks for everything. Happy New Year

Thank you so much! It makes me glad to know that you enjoy this program. Happy New Year to you too! 🎆

**Comment by ArturKovacs** [comment]
On top of the missing documentation, there was a bug in the code that prevented the alphanumeric `-` key from triggering actions bound to `subtract`

**Comment by akimdi** [comment]
> key from triggering actions bound to `subtract`

@ArturKovacs  Thank you.

**Comment by ArturKovacs** [comment]
You're welcome

**Pull request merged**
