### PR TITLE
Add new scaling mode and buttons for scaling modes.

### LINKED ISSUE #88: Provide a "Fit to screen" mode that does not scale up small images
When scrolling through a folder with images of different sizes I find myself switching between "Fit to screen" and "Original size" view modes often: smaller images look bad when blown up to the entire screen and are better viewed in their original size, but after I switch to the original size and encounter an image larger than my screen I have to switch back to "Fit to screen" mode to see them. This quickly becomes tedious.

FWIW most other viewers seem to default to showing the image at the original size if it's smaller than the screen, but fit larger images to screen.

### PR DESCRIPTION
**Pull request by ArturKovacs**
Closes #88.

### CODE REVIEW

**Comment by ArturKovacs** [comment]
@Shnatsel check this and see if this satisfies #88.

**Comment by ArturKovacs** [comment]
Note to self: The info panel needs to be updated to reflect the new keyboard inputs. While I'm at it might as well add Enter for toggling full-screen.

**Comment by Shnatsel** [comment]
Yes it does! Love the icons btw, they communicate what the different modes do very clearly.

**Comment by ArturKovacs** [comment]
Thank you :))

**Pull request merged**
