### PR TITLE
Implement changing image via the Page Up and Page Down keys

### PR DESCRIPTION
**Pull request by paolobarbolini**

### CODE REVIEW

**Comment by ArturKovacs** [comment]
All users can set custom key-bindings through the cfg.toml file. What is the argument for making this default?

**Comment by paolobarbolini** [comment]
Because other image viewers have it set by default

**Comment by ArturKovacs** [comment]
Yeah that sounds like a pretty good argument. Just out of curiosity can you list a few more widely used ones?

**Comment by ArturKovacs** [comment]
I'm a bit sad you didn't respond :( but anyhow, this should be perfectly fine to merge, I don't think that those two keys should have any other functionality.

I'd just like to ask you add these keys to the Bindings.md file (in the root) to the example config snippet. Like

```toml
[bindings]
img_next = ["d", "right", "pagedown"]
img_prev = ["a", "left", "pageup"]
```

And then this is good to merge.

**Comment by paolobarbolini** [comment]
Fixed, sorry I didn't answer before. Anyway those were the keyboard shortcuts I'm interested in at the moment.

**Comment by ArturKovacs** [comment]
Thanks!

**Pull request merged**
